version: '2'
services:
  enrollments-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/enrollments/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=enrollments
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
